version: "3.9"

services:
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: veloura-product-service
    ports:
      - "5002:5002"
    env_file:
      - .env
    environment:
      - MONGODB_URI=${MONGODB_URI}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: product-service-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
